name: Build Dotnet.

on: 
  - workflow_dispatch
  - push

env:
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '18.16.0'
  SOLUTION_PATH: './DotnetIntegratonTestSample.sln'
  BUILD_CONFIGURATION: 'Release'
  FUNCTION_APP_PATH: './src/FunctionApp/FunctionApp'
  
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: P@ssw0rd
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
        options: --restart=always
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_PATH }}

      - name: setup local.settings.json
        run: cp ./src/FunctionApp/local.settings.json.template ./src/FunctionApp/local.settings.json
      
      - name: Unit test
        run: dotnet test ${{ env.SOLUTION_PATH }} --filter "Category!=Integration"
                    
      - name: Integration test
        run: dotnet test ${{ env.SOLUTION_PATH }} --filter "Category=Integration"
